---
# tasks file for centos_automatic_updates

# ===
#
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html
#
# https://dnf.readthedocs.io/en/latest/automatic.html
#
# ===

- name: ensure that the "dnf-automatic" package is installed
  dnf:
    name:
      - dnf-automatic
    state: present

- name: ensure that "dnf-automatic.timer" is enabled, running and is not masked
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes
    masked: no

- name: Fetch "/etc/dnf/automatic.conf" and store the configuration file in a "backups" directory under the "files" directory
  fetch:
    src: /etc/dnf/automatic.conf
    dest: roles/centos_automatic_updates/files/backups/{{ inventory_hostname }}/{{ ansible_facts['date_time']['iso8601'] }}-{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}/
    flat: yes
    validate_checksum: yes
    fail_on_missing: no

- name: copy a custom "automatic.conf" file into place, backing up the original if it differs from the copied version
  copy:
    src: dnf-automatic/automatic.conf
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: restart "dnf-automatic.timer", in all cases, also issue daemon-reload to pick up configuration changes
  systemd:
    name: dnf-automatic.timer
    state: restarted
    daemon_reload: yes
